### ISSUE TITLE
tree .git does not work on windows

### ISSUE THREAD

**Issue by nagjamna** [githubschool/daylight-awesome#20]
@hollenberry 
Thank you for the wonderful sessions. It helped a lot.
I was trying to do in command line to get the view of tree structure of git (Which shows tags, branches, objects etc).

tree .git
In windows, it shows command not found. How to make it work?
Thanks,
Nagendran

**Comment by hollenberry** [comment]
👋 @nagjamna ! 

I've been able to use `tree` because I downloaded it as a package from Homebrew, which is exclusive to macOS. 

Depending on your environment set up, you should be able to use tree on your machine as well. This is a start, and has a few solutions to get you set up: https://superuser.com/questions/531592/how-do-i-add-the-tree-command-to-git-bash-on-windows

Please let me know if I can help troubleshoot any further, or if that resource helps!

**Comment by nagjamna** [comment]
Thanks Eric.
It worked in windows also. Closing the issue also :+1:
